/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrainingsRouteImport } from './routes/_app.trainings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlatformRouteImport } from './routes/_app.platform'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppOrgRouteImport } from './routes/_app.org'
import { Route as AppOffersRouteImport } from './routes/_app.offers'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLeavesRouteImport } from './routes/_app.leaves'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppInvitationsRouteImport } from './routes/_app.invitations'
import { Route as AppInterviewsRouteImport } from './routes/_app.interviews'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCandidatesRouteImport } from './routes/_app.candidates'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppEmployeesIdRouteImport } from './routes/_app.employees.$id'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainingsRoute = AppTrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformRoute = AppPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLeavesRoute = AppLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppInvitationsRoute = AppInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsRoute = AppInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AppAdminRoute
  '/attendance': typeof AppAttendanceRoute
  '/billing': typeof AppBillingRoute
  '/candidates': typeof AppCandidatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/interviews': typeof AppInterviewsRoute
  '/invitations': typeof AppInvitationsRoute
  '/jobs': typeof AppJobsRoute
  '/leaves': typeof AppLeavesRoute
  '/notifications': typeof AppNotificationsRoute
  '/offers': typeof AppOffersRoute
  '/org': typeof AppOrgRoute
  '/performance': typeof AppPerformanceRoute
  '/platform': typeof AppPlatformRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/trainings': typeof AppTrainingsRoute
  '/employees/$id': typeof AppEmployeesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AppAdminRoute
  '/attendance': typeof AppAttendanceRoute
  '/billing': typeof AppBillingRoute
  '/candidates': typeof AppCandidatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/interviews': typeof AppInterviewsRoute
  '/invitations': typeof AppInvitationsRoute
  '/jobs': typeof AppJobsRoute
  '/leaves': typeof AppLeavesRoute
  '/notifications': typeof AppNotificationsRoute
  '/offers': typeof AppOffersRoute
  '/org': typeof AppOrgRoute
  '/performance': typeof AppPerformanceRoute
  '/platform': typeof AppPlatformRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/trainings': typeof AppTrainingsRoute
  '/employees/$id': typeof AppEmployeesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/candidates': typeof AppCandidatesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/employees': typeof AppEmployeesRouteWithChildren
  '/_app/interviews': typeof AppInterviewsRoute
  '/_app/invitations': typeof AppInvitationsRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/leaves': typeof AppLeavesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/offers': typeof AppOffersRoute
  '/_app/org': typeof AppOrgRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/platform': typeof AppPlatformRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/trainings': typeof AppTrainingsRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/admin'
    | '/attendance'
    | '/billing'
    | '/candidates'
    | '/dashboard'
    | '/documents'
    | '/employees'
    | '/interviews'
    | '/invitations'
    | '/jobs'
    | '/leaves'
    | '/notifications'
    | '/offers'
    | '/org'
    | '/performance'
    | '/platform'
    | '/profile'
    | '/reports'
    | '/trainings'
    | '/employees/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/admin'
    | '/attendance'
    | '/billing'
    | '/candidates'
    | '/dashboard'
    | '/documents'
    | '/employees'
    | '/interviews'
    | '/invitations'
    | '/jobs'
    | '/leaves'
    | '/notifications'
    | '/offers'
    | '/org'
    | '/performance'
    | '/platform'
    | '/profile'
    | '/reports'
    | '/trainings'
    | '/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/_app/admin'
    | '/_app/attendance'
    | '/_app/billing'
    | '/_app/candidates'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/employees'
    | '/_app/interviews'
    | '/_app/invitations'
    | '/_app/jobs'
    | '/_app/leaves'
    | '/_app/notifications'
    | '/_app/offers'
    | '/_app/org'
    | '/_app/performance'
    | '/_app/platform'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/trainings'
    | '/_app/employees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trainings': {
      id: '/_app/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof AppTrainingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform': {
      id: '/_app/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AppPlatformRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org': {
      id: '/_app/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaves': {
      id: '/_app/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AppLeavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invitations': {
      id: '/_app/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AppInvitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews': {
      id: '/_app/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AppInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates': {
      id: '/_app/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
  }
}

interface AppEmployeesRouteChildren {
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesIdRoute: AppEmployeesIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCandidatesRoute: typeof AppCandidatesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppInterviewsRoute: typeof AppInterviewsRoute
  AppInvitationsRoute: typeof AppInvitationsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppLeavesRoute: typeof AppLeavesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOffersRoute: typeof AppOffersRoute
  AppOrgRoute: typeof AppOrgRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPlatformRoute: typeof AppPlatformRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTrainingsRoute: typeof AppTrainingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBillingRoute: AppBillingRoute,
  AppCandidatesRoute: AppCandidatesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppInterviewsRoute: AppInterviewsRoute,
  AppInvitationsRoute: AppInvitationsRoute,
  AppJobsRoute: AppJobsRoute,
  AppLeavesRoute: AppLeavesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOffersRoute: AppOffersRoute,
  AppOrgRoute: AppOrgRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPlatformRoute: AppPlatformRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppTrainingsRoute: AppTrainingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
